### ISSUE TITLE
emacs-jest assumes jest is located on the user's path

### ISSUE THREAD

**Issue by joeheyming** [Emiller88/emacs-jest#2]
I was excited to use emacs-jest, but when I tried it out I got:
/bin/sh jest: command not found.

Could it be possible to make it so that this package looks for jest in the module?  Like it could try to find the nearest package.json and execute jest from the node_modules in that folder.

I've used other packages like grunt.el https://github.com/gempesaw/grunt.el  and it has similar behavior where it tries to find the nearest package json to run grunt.

**Comment by sunesimonsen** [comment]
Take a look at locate-dominating-file. You can use it to find the first path containing node_modules/.bin/jest

**Comment by joewreschnig** [comment]
Also consider use of `executable-find` if you continue using `sh`. I do have the node_modules bin path in my `exec-path`, but `jest--run-as-comint` runs `jest` through `sh`, so it doesn't inherit the Emacs executable  path. If you're going to wrap the execution, you should also invoke the executable through a fully-qualified path.

**Comment by ryanolsonx** [comment]
Try https://github.com/codesuki/add-node-modules-path

**Comment by Eeemil** [comment]
> Try https://github.com/codesuki/add-node-modules-path

does not solve this issue

**Comment by Aigeruth** [comment]
I mainly use Jest for React development and these projects are created with the `create-react-app` command. This means that Jest is configured for `npm test`. I already have `npm` in the `PATH`, so I ended up with the following configuration:

```lisp
(use-package jest
  :config
  (setq jest-executable "npm test --")
)
```

**Comment by baerrach** [comment]
There is already an emacs package that will add your project's `node_modules` to the shell path

```
(use-package add-node-modules-path
  :after (js2-mode))
```

@eemil I have everything working with `add-node-modules-path` and `(setq jest-executable "npm test --")` what is not working for you?

**Comment by baerrach** [comment]
> 
> 
> I mainly use Jest for React development and these projects are created with the `create-react-app` command. This means that Jest is configured for `npm test`. I already have `npm` in the `PATH`, so I ended up with the following configuration:
> 
> ```lisp
> (use-package jest
>   :config
>   (setq jest-executable "npm test --")
> )
> ```

You want to use this anyway. As it centralises the configuration of jest.

We need to add `cross-env NODE_PATH-.` to the `test script` so running `jest` manually would also need that too. Much easier to stick with `npm t` and configure `package.json` properly

**Comment by edmundmiller** [comment]
Sorry for taking forever to get around to this, and being a poor maintainer so far, this is my first barely popular project.

@baerrach I'm testing the "npm test --" and it's working great. So great that it works with `ava`, and I'm going to guess anything you could want as long as it's under your `test` script.

Could you expand on your `cross-env NODE_PATH-.` comment? 

I don't know whether to rename the repo to something else, maybe just make a note of it in the README, archive the project or what. Any comments on that would be appreciated.

**Comment by baerrach** [comment]
Our project has `import` or `require` statements for **local** src modules as `path/to/module`.

Its a bit equivalent to webpack alias https://webpack.js.org/configuration/resolve/

By setting `NODE_PATH=.` as an environment variable then node will [load the module from the global folders](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders).

To work on both Windows and Unix environments I **was** using `cross-env` to see these environment variables.

I've since abandoned that because `cross-env` has some issues with signal handling `Ctrl-C` properly and passing them to the spawned child processes.

Now I just recommend Windows users to use https://gitforwindows.org/ and set their shell correctly to export `NODE_PATH=.` and use the Bash shell provided.

**Comment by edmundmiller** [comment]
Gotcha so it's just windows? But with the `npm test --` from @Aigeruth it should work, so I'm going to go ahead and close it. 

Sidenote I use yarn on some projects but I went with npm because everyone should have npm, but not everyone needs yarn, and it works with `npm test --`

I also didn't give proper credit to @Aigeruth in the commit, I apologize, I read @baerrach's, quote.
