### ISSUE TITLE
emacs-jest assumes that jest options are in project root

### ISSUE THREAD

**Issue by tomoyoirl** [Emiller88/emacs-jest#4]
My project does not store the Jest configuration in the project root. It stores the Jest configuration in `web/react`, where the relevant code lives. This directory includes files such as:
- `jest.config.js`
- `package.json`

Other project directories include code in other programming languages. There is no `package.json` in `project/` or `project/web`.

#2 discusses the difficulty in finding the `jest` executable, but even if I hardcode a working executable, when I try to invoke `jest-file` on `/Users/thomaswhaples/code/project/web/react/src/ReactAppName/SubApp/Component/__tests__/Form.spec.jsx` 

then the process runs in `/Users/thomaswhaples/code/project` instead of `/Users/thomaswhaples/code/project/web/react`. As a result, I have to hardcode an additional paramter:

```
--config web/react/package.json
```

This is inconvenient to set up, glues the configuration to one specific project, and generally should not be necessary.

**Comment by edmundmiller** [comment]
@twhaples I'll look for a fix for this. For now could you consider setting the variable in a `dir-locals.el`? That would fix `glues the configuration to one specific project` hopefully

**Comment by edmundmiller** [comment]
I'm going close this since b51be19c1de9e82ee1dc62921be2222fc5685eed should work for most use cases and possibly even yours. If anyone has another non-conventional setup like this I recommend using `dir-locals.el` for that project to set where your config is for that project.

[Quick link if you've never used it before](https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Local-Variables.html) 

@twhaples, you're welcome to reopen this if you have another fix or b51be19c1de9e82ee1dc62921be2222fc5685eed doesn't solve this.
